[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"

chain_id = 5
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "@chainlink/=lib/chainlink-brownie-contracts"]

[rpc_endpoints]
goerli = "PlaceYourRpc"

[etherscan]
goerli = { key = "${GOERLI_KEY}" }